spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}/${DATABASE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_USER_PASSWORD}